disabled_rules: # rule identifiers to exclude from running
  #- force_cast
  #- force_try
  - todo
  - identifier_name
  - line_length
  - multiple_closures_with_trailing_closure
  - type_name
  # - cyclomatic_complexity
  #- function_body_length
  #- file_length
  - type_body_length
  - function_parameter_count
  - notification_center_detachment

opt_in_rules:
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - first_where
  - identical_operands
  - let_var_whitespace
  - overridden_super_call
  - prohibited_interface_builder
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - yoda_condition
  - discouraged_optional_boolean

nesting:
  type_level: 2

excluded:
  - Pods

