default_platform(:ios)
platform :ios do
 	desc "Description of what the lane does"
  	lane :tests do
		desc "Testing the app"
        	run_tests(scheme: "DiffableDataSourceTestApp")
  	end

  	lane :create_app do
		desc "Create new app version"
  		produce
  	end

  	lane :screenshot do
    	snapshot
	end
	  
	lane :refreshJenkinsKeychain do
		delete_keychain(name: "jenkins") if File.exists? File.expand_path("~/Library/Keychains/jenkins-db")
  		create_keychain(
    	name: "jenkins",
    	password: "jenkins",
    	timeout: false,
    	lock_when_sleeps: false,
    	unlock: true
  	)
	end

	lane :matchPopulateJenkinsKeychain do
		register_devices(devices_file: "./fastlane/devices.txt")
	  
		match(
		  type: "adhoc",
		  app_identifier: [
			"com.goran.DiffableDataSourceTestApp"
		  ]
		)
		match(
		  type: "development",
		  app_identifier: [
			"com.goran.DiffableDataSourceTestApp"
		  ]
		)
		match(
		  type: "appstore",
		  app_identifier: [
			"com.goran.DiffableDataSourceTestApp"
		  ]
		)
	end

	lane :installPods do 
		cocoapods(
			clean_install: true,
			podfile: "Podfile"
		  )
	end

	desc "Run unit and ui tests"
 	lane :runTests do
    	run_tests(
      		scheme: "DiffableDataSourceTestApp",
    	)
  	end

  	desc "Create coverage html"
  	lane :createCoverageReport do
    	slather(
      		scheme: "DiffableDataSourceTestApp",
      		proj: "DiffableDataSourceTestApp.xcodeproj",
      		html: true,
      		ignore: [
        		"Pods/*",
        		"DiffableDataSourceTestApp/Library/*"
      		]
    	)
  	end

	lane :beta do
	
		cert
  		sigh(force: true)
		
		increment_build_number(
      			build_number: latest_testflight_build_number() + 1,
      			xcodeproj: "./DiffableDataSourceTestApp.xcodeproj"
    		)
		
		clear_derived_data
  		build_app(
			scheme: "DiffableDataSourceTestApp",
			clean: true
		)

  		# Upload the application to Testflight
		upload_to_testflight(
			skip_waiting_for_build_processing: true,
  			beta_app_feedback_email: "goran.tokovic@digitalatrium.rs",
  			beta_app_description: "Beta app description",
			beta_app_review_info: {
    				contact_email: "goran.tokovic@digitalatrium.rs",
    				contact_first_name: "Goran",
    				contact_last_name: "Tokovic",
    				contact_phone: "+381643513338",
    				demo_account_name: "test@test.com",
    				demo_account_password: "12345678",
    				notes: "this is review note for the reviewer <3 thank you for reviewing"
  			},
			localized_build_info: {
    				"default": {
      					whats_new: "What is new in this version",
    				},
  			},
			groups: ["Public Group"]
		)

		slack(
           		message: "Successfully distributed a new beta build",
           		success: true,
           		slack_url: "https://hooks.slack.com/services/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",
       		)
	end
end