default_platform(:ios)
platform :ios do
  desc "Description of what the lane does"
  lane :tests do
	desc "Testing the app"
        run_tests(scheme: "DiffableDataSourceTestApp")
  end

  lane :beta do
	desc "Building the app"
  	build_app(scheme: "DiffableDataSourceTestApp")
  end
end